// Dig 子网映射信息
// 用于记录不同地区和 ISP 的子网信息

export interface SubnetInfo {
    /** 国家 */
    "country": string;
    /** 大区 */
    "region": string;
    /** 省份 */
    "province": string;
    /** ISP 服务商 */
    "isp": string;
    /** 子网地址 (CIDR格式，如: 192.168.1.0) */
    "subnet": string;
}

/**
 * 子网信息映射表
 * 
 * 格式说明：
 * - "country": 国家名称，如 "中国"、"美国"
 * - "region": 大区名称，如 "华东"、"华北"、"西部"
 * - "province": 省份名称，如 "上海"、"北京"、"广东"
 * - "isp": ISP 服务商，如 "电信"、"联通"、"移动"、"Cloudflare"
 * - "subnet": 子网地址，CIDR 格式，如 "101.249.112.0"
 * 
 * 使用示例：
 * ```typescript
 * import { subnetMap, findSubnetInfo } from '@/lib/dig-map';
 */
export const subnetMap: SubnetInfo[] = [
    { "country": "中国", "region": "西南", "province": "重庆", "isp": "电信", "subnet": "119.84.87.0" },
    { "country": "中国", "region": "西南", "province": "贵州", "isp": "电信", "subnet": "222.87.129.0" },
    { "country": "中国", "region": "西南", "province": "西藏", "isp": "电信", "subnet": "101.249.112.0" },
    { "country": "中国", "region": "西南", "province": "四川", "isp": "电信", "subnet": "139.201.125.0" },
    { "country": "中国", "region": "西南", "province": "云南", "isp": "电信", "subnet": "112.117.218.0" },
    { "country": "中国", "region": "西北", "province": "青海", "isp": "电信", "subnet": "223.220.250.0" },
    { "country": "中国", "region": "西北", "province": "陕西", "isp": "电信", "subnet": "106.36.41.0" },
    { "country": "中国", "region": "西北", "province": "甘肃", "isp": "电信", "subnet": "60.164.222.0" },
    { "country": "中国", "region": "西北", "province": "新疆", "isp": "电信", "subnet": "110.157.232.0" },
    { "country": "中国", "region": "西北", "province": "宁夏", "isp": "电信", "subnet": "218.95.142.0" },
    { "country": "中国", "region": "华南", "province": "福建", "isp": "电信", "subnet": "117.27.142.0" },
    { "country": "中国", "region": "华南", "province": "湖南", "isp": "电信", "subnet": "175.6.2.0" },
    { "country": "中国", "region": "华南", "province": "海南", "isp": "电信", "subnet": "112.67.250.0" },
    { "country": "中国", "region": "华南", "province": "广西", "isp": "电信", "subnet": "116.10.187.0" },
    { "country": "中国", "region": "华南", "province": "广东", "isp": "电信", "subnet": "183.61.64.0" },
    { "country": "中国", "region": "华北", "province": "河南", "isp": "电信", "subnet": "222.88.93.0" },
    { "country": "中国", "region": "华北", "province": "河北", "isp": "电信", "subnet": "124.239.186.0" },
    { "country": "中国", "region": "华北", "province": "山西", "isp": "电信", "subnet": "59.49.85.0" },
    { "country": "中国", "region": "华北", "province": "山东", "isp": "电信", "subnet": "150.138.216.0" },
    { "country": "中国", "region": "华北", "province": "天津", "isp": "电信", "subnet": "123.150.203.0" },
    { "country": "中国", "region": "华北", "province": "北京", "isp": "电信", "subnet": "106.38.179.0" },
    { "country": "中国", "region": "华北", "province": "内蒙古", "isp": "电信", "subnet": "1.180.236.0" },
    { "country": "中国", "region": "华东", "province": "湖北", "isp": "电信", "subnet": "119.97.160.0" },
    { "country": "中国", "region": "华东", "province": "浙江", "isp": "电信", "subnet": "183.158.35.0" },
    { "country": "中国", "region": "华东", "province": "江西", "isp": "电信", "subnet": "117.21.201.0" },
    { "country": "中国", "region": "华东", "province": "江苏", "isp": "电信", "subnet": "58.222.18.0" },
    { "country": "中国", "region": "华东", "province": "安徽", "isp": "电信", "subnet": "61.132.239.0" },
    { "country": "中国", "region": "华东", "province": "上海", "isp": "电信", "subnet": "101.227.182.0" },
    { "country": "中国", "region": "东北", "province": "黑龙江", "isp": "电信", "subnet": "219.147.157.0" },
    { "country": "中国", "region": "东北", "province": "辽宁", "isp": "电信", "subnet": "59.47.0.0" },
    { "country": "中国", "region": "东北", "province": "吉林", "isp": "电信", "subnet": "36.48.159.0" },
    { "country": "中国", "region": "西南", "province": "重庆", "isp": "联通", "subnet": "113.207.123.0" },
    { "country": "中国", "region": "西南", "province": "贵州", "isp": "联通", "subnet": "58.16.246.0" },
    { "country": "中国", "region": "西南", "province": "西藏", "isp": "联通", "subnet": "221.13.85.0" },
    { "country": "中国", "region": "西南", "province": "四川", "isp": "联通", "subnet": "221.10.205.0" },
    { "country": "中国", "region": "西南", "province": "云南", "isp": "联通", "subnet": "14.204.74.0" },
    { "country": "中国", "region": "西北", "province": "青海", "isp": "联通", "subnet": "43.242.182.0" },
    { "country": "中国", "region": "西北", "province": "陕西", "isp": "联通", "subnet": "123.138.60.0" },
    { "country": "中国", "region": "西北", "province": "甘肃", "isp": "联通", "subnet": "180.95.233.0" },
    { "country": "中国", "region": "西北", "province": "新疆", "isp": "联通", "subnet": "60.13.248.0" },
    { "country": "中国", "region": "西北", "province": "宁夏", "isp": "联通", "subnet": "116.172.71.0" },
    { "country": "中国", "region": "华南", "province": "福建", "isp": "联通", "subnet": "36.250.64.0" },
    { "country": "中国", "region": "华南", "province": "湖南", "isp": "联通", "subnet": "220.202.121.0" },
    { "country": "中国", "region": "华南", "province": "海南", "isp": "联通", "subnet": "153.0.152.0" },
    { "country": "中国", "region": "华南", "province": "广西", "isp": "联通", "subnet": "121.31.6.0" },
    { "country": "中国", "region": "华南", "province": "广东", "isp": "联通", "subnet": "27.36.118.0" },
    { "country": "中国", "region": "华北", "province": "河南", "isp": "联通", "subnet": "182.118.241.0" },
    { "country": "中国", "region": "华北", "province": "河北", "isp": "联通", "subnet": "121.18.209.0" },
    { "country": "中国", "region": "华北", "province": "山西", "isp": "联通", "subnet": "124.163.220.0" },
    { "country": "中国", "region": "华北", "province": "山东", "isp": "联通", "subnet": "123.132.254.0" },
    { "country": "中国", "region": "华北", "province": "天津", "isp": "联通", "subnet": "60.28.117.0" },
    { "country": "中国", "region": "华北", "province": "北京", "isp": "联通", "subnet": "111.206.105.0" },
    { "country": "中国", "region": "华北", "province": "内蒙古", "isp": "联通", "subnet": "1.31.174.0" },
    { "country": "中国", "region": "华东", "province": "湖北", "isp": "联通", "subnet": "113.57.219.0" },
    { "country": "中国", "region": "华东", "province": "浙江", "isp": "联通", "subnet": "60.12.107.0" },
    { "country": "中国", "region": "华东", "province": "江西", "isp": "联通", "subnet": "118.212.134.0" },
    { "country": "中国", "region": "华东", "province": "江苏", "isp": "联通", "subnet": "153.101.64.0" },
    { "country": "中国", "region": "华东", "province": "安徽", "isp": "联通", "subnet": "58.242.249.0" },
    { "country": "中国", "region": "华东", "province": "上海", "isp": "联通", "subnet": "112.65.226.0" },
    { "country": "中国", "region": "东北", "province": "黑龙江", "isp": "联通", "subnet": "221.212.217.0" },
    { "country": "中国", "region": "东北", "province": "辽宁", "isp": "联通", "subnet": "124.95.189.0" },
    { "country": "中国", "region": "东北", "province": "吉林", "isp": "联通", "subnet": "175.20.242.0" },
    { "country": "中国", "region": "西南", "province": "重庆", "isp": "中国移动", "subnet": "183.230.75.0" },
    { "country": "中国", "region": "西南", "province": "贵州", "isp": "中国移动", "subnet": "117.187.20.0" },
    { "country": "中国", "region": "西南", "province": "西藏", "isp": "中国移动", "subnet": "111.11.197.0" },
    { "country": "中国", "region": "西南", "province": "四川", "isp": "中国移动", "subnet": "117.172.6.0" },
    { "country": "中国", "region": "西南", "province": "云南", "isp": "中国移动", "subnet": "39.130.136.0" },
    { "country": "中国", "region": "西北", "province": "青海", "isp": "中国移动", "subnet": "111.44.244.0" },
    { "country": "中国", "region": "西北", "province": "陕西", "isp": "中国移动", "subnet": "218.200.14.0" },
    { "country": "中国", "region": "西北", "province": "甘肃", "isp": "中国移动", "subnet": "117.156.245.0" },
    { "country": "中国", "region": "西北", "province": "新疆", "isp": "中国移动", "subnet": "117.145.179.0" },
    { "country": "中国", "region": "西北", "province": "宁夏", "isp": "中国移动", "subnet": "211.138.60.0" },
    { "country": "中国", "region": "华南", "province": "福建", "isp": "中国移动", "subnet": "112.5.252.0" },
    { "country": "中国", "region": "华南", "province": "湖南", "isp": "中国移动", "subnet": "111.23.14.0" },
    { "country": "中国", "region": "华南", "province": "海南", "isp": "中国移动", "subnet": "221.182.135.0" },
    { "country": "中国", "region": "华南", "province": "广西", "isp": "中国移动", "subnet": "111.12.25.0" },
    { "country": "中国", "region": "华南", "province": "广东", "isp": "中国移动", "subnet": "183.232.213.0" },
    { "country": "中国", "region": "华北", "province": "河南", "isp": "中国移动", "subnet": "211.142.193.0" },
    { "country": "中国", "region": "华北", "province": "河北", "isp": "中国移动", "subnet": "111.11.31.0" },
    { "country": "中国", "region": "华北", "province": "山西", "isp": "中国移动", "subnet": "183.203.13.0" },
    { "country": "中国", "region": "华北", "province": "山东", "isp": "中国移动", "subnet": "112.54.83.0" },
    { "country": "中国", "region": "华北", "province": "天津", "isp": "中国移动", "subnet": "117.131.215.0" },
    { "country": "中国", "region": "华北", "province": "北京", "isp": "中国移动", "subnet": "111.13.113.0" },
    { "country": "中国", "region": "华北", "province": "内蒙古", "isp": "中国移动", "subnet": "218.202.111.0" },
]

// 为了开发，将subnetMap拆出来只处理一部分，方便快速调试
export const subnetMapOther: SubnetInfo[] = [
    { "country": "中国", "region": "华东", "province": "湖北", "isp": "中国移动", "subnet": "111.47.204.0" },
    { "country": "中国", "region": "华东", "province": "浙江", "isp": "中国移动", "subnet": "111.1.36.0" },
    { "country": "中国", "region": "华东", "province": "江西", "isp": "中国移动", "subnet": "117.169.15.0" },
    { "country": "中国", "region": "华东", "province": "江苏", "isp": "中国移动", "subnet": "112.21.165.0" },
    { "country": "中国", "region": "华东", "province": "安徽", "isp": "中国移动", "subnet": "120.209.134.0" },
    { "country": "中国", "region": "华东", "province": "上海", "isp": "中国移动", "subnet": "117.185.122.0" },
    { "country": "中国", "region": "东北", "province": "黑龙江", "isp": "中国移动", "subnet": "111.40.170.0" },
    { "country": "中国", "region": "东北", "province": "辽宁", "isp": "中国移动", "subnet": "221.180.248.0" },
    { "country": "中国", "region": "东北", "province": "吉林", "isp": "中国移动", "subnet": "111.26.136.0" },
    { "country": "中国", "region": "西南", "province": "重庆", "isp": "长城宽带", "subnet": "211.162.213.0" },
    { "country": "中国", "region": "西南", "province": "重庆", "isp": "中国铁通", "subnet": "222.55.13.0" },
    { "country": "中国", "region": "西南", "province": "四川", "isp": "长城宽带", "subnet": "211.162.177.0" },
    { "country": "中国", "region": "西南", "province": "四川", "isp": "长城宽带", "subnet": "180.91.103.0" },
    { "country": "中国", "region": "西南", "province": "四川", "isp": "中国铁通", "subnet": "123.71.254.0" },
    { "country": "中国", "region": "西南", "province": "云南", "isp": "长城宽带", "subnet": "117.75.19.0" },
    { "country": "中国", "region": "西北", "province": "陕西", "isp": "长城宽带", "subnet": "101.247.51.0" },
    { "country": "中国", "region": "西北", "province": "陕西", "isp": "中国铁通", "subnet": "61.236.251.0" },
    { "country": "中国", "region": "西北", "province": "陕西", "isp": "教育网", "subnet": "202.117.4.0" },
    { "country": "中国", "region": "西北", "province": "甘肃", "isp": "教育网", "subnet": "222.23.55.0" },
    { "country": "中国", "region": "华南", "province": "福建", "isp": "长城宽带", "subnet": "211.162.39.0" },
    { "country": "中国", "region": "华南", "province": "福建", "isp": "教育网", "subnet": "121.192.176.0" },
    { "country": "中国", "region": "华南", "province": "湖南", "isp": "中国铁通", "subnet": "122.72.123.0" },
    { "country": "中国", "region": "华南", "province": "广西", "isp": "中国铁通", "subnet": "222.52.39.0" },
    { "country": "中国", "region": "华南", "province": "广东", "isp": "长城宽带", "subnet": "211.162.51.0" },
    { "country": "中国", "region": "华南", "province": "广东", "isp": "中国铁通", "subnet": "122.72.52.0" },
    { "country": "中国", "region": "华南", "province": "广东", "isp": "教育网", "subnet": "202.116.160.0" },
    { "country": "中国", "region": "华北", "province": "河南", "isp": "长城宽带", "subnet": "61.136.96.0" },
    { "country": "中国", "region": "华北", "province": "河北", "isp": "长城宽带", "subnet": "175.188.163.0" },
    { "country": "中国", "region": "华北", "province": "河北", "isp": "中国铁通", "subnet": "222.38.131.0" },
    { "country": "中国", "region": "华北", "province": "山东", "isp": "教育网", "subnet": "202.194.19.0" },
    { "country": "中国", "region": "华北", "province": "天津", "isp": "长城宽带", "subnet": "211.161.80.0" },
    { "country": "中国", "region": "华北", "province": "北京", "isp": "长城宽带", "subnet": "124.193.0.0" },
    { "country": "中国", "region": "华北", "province": "北京", "isp": "中国铁通", "subnet": "222.35.78.0" },
    { "country": "中国", "region": "华北", "province": "北京", "isp": "教育网", "subnet": "222.199.191.0" },
    { "country": "中国", "region": "华东", "province": "湖北", "isp": "长城宽带", "subnet": "103.43.208.0" },
    { "country": "中国", "region": "华东", "province": "湖北", "isp": "中国铁通", "subnet": "222.42.5.0" },
    { "country": "中国", "region": "华东", "province": "湖北", "isp": "教育网", "subnet": "59.68.77.0" },
    { "country": "中国", "region": "华东", "province": "浙江", "isp": "中国铁通", "subnet": "222.46.123.0" },
    { "country": "中国", "region": "华东", "province": "浙江", "isp": "教育网", "subnet": "210.32.125.0" },
    { "country": "中国", "region": "华东", "province": "江苏", "isp": "长城宽带", "subnet": "211.162.27.0" },
    { "country": "中国", "region": "华东", "province": "江苏", "isp": "教育网", "subnet": "202.119.25.0" },
    { "country": "中国", "region": "华东", "province": "安徽", "isp": "长城宽带", "subnet": "211.162.1.0" },
    { "country": "中国", "region": "华东", "province": "上海", "isp": "长城宽带", "subnet": "124.14.9.0" },
    { "country": "中国", "region": "华东", "province": "上海", "isp": "中国铁通", "subnet": "122.72.6.0" },
    { "country": "中国", "region": "华东", "province": "上海", "isp": "教育网", "subnet": "202.120.1.0" },
    { "country": "中国", "region": "东北", "province": "黑龙江", "isp": "教育网", "subnet": "202.118.236.0" },
    { "country": "中国", "region": "东北", "province": "辽宁", "isp": "长城宽带", "subnet": "175.190.19.0" },
    { "country": "中国", "region": "东北", "province": "辽宁", "isp": "中国铁通", "subnet": "122.72.50.0" },
    { "country": "中国", "region": "东北", "province": "吉林", "isp": "长城宽带", "subnet": "49.221.17.0" },
    { "country": "中国", "region": "东北", "province": "吉林", "isp": "中国铁通", "subnet": "122.72.53.0" },
    { "country": "中国", "region": "东北", "province": "吉林", "isp": "教育网", "subnet": "202.198.17.0" },
    { "country": "澳大利亚", "region": "", "province": "昆士兰州", "isp": "teletechnique.com", "subnet": "103.194.127.0" },
    { "country": "新西兰", "region": "", "province": "威灵顿", "isp": "spark.co.nz", "subnet": "122.63.22.0" },
    { "country": "墨西哥", "region": "", "province": "韦拉克鲁斯", "isp": "cablemas.com.mx", "subnet": "189.220.1.0" },
    { "country": "墨西哥", "region": "", "province": "科利马", "isp": "megacable.com.mx", "subnet": "177.227.38.0" },
    { "country": "墨西哥", "region": "", "province": "新莱昂", "isp": "telcel.com", "subnet": "200.68.164.0" },
    { "country": "墨西哥", "region": "", "province": "新莱昂", "isp": "alestra.mx", "subnet": "148.244.217.0" },
    { "country": "墨西哥", "region": "", "province": "墨西哥州", "isp": "totalplay.com.mx", "subnet": "187.190.157.0" },
    { "country": "墨西哥", "region": "", "province": "塔毛利帕斯州", "isp": "cablevision.com.mx", "subnet": "201.175.99.0" },
    { "country": "墨西哥", "region": "", "province": "克雷塔罗州", "isp": "metrored.com.mx", "subnet": "177.232.84.0" },
    { "country": "墨西哥", "region": "", "province": "伊达尔戈", "isp": "telmex.mx", "subnet": "189.232.74.0" },
    { "country": "格陵兰", "region": "", "province": "Greenland", "isp": "tele.gl", "subnet": "46.16.17.0" },
    { "country": "加拿大", "region": "", "province": "安大略", "isp": "cogecopeer1.com", "subnet": "76.74.142.0" },
    { "country": "阿根廷", "region": "", "province": "布宜诺斯艾利斯", "isp": "telecom.com.ar", "subnet": "181.166.248.0" },
    { "country": "秘鲁", "region": "", "province": "皮乌拉地区", "isp": "internexa.com", "subnet": "190.108.82.0" },
    { "country": "智利", "region": "", "province": "圣地亚哥首都大区", "isp": "tie.cl", "subnet": "186.30.249.0" },
    { "country": "巴西", "region": "", "province": "圣保罗", "isp": "claro.com.br", "subnet": "201.6.246.0" },
    { "country": "巴拿马", "region": "", "province": "巴拿马城", "isp": "cableonda.com", "subnet": "201.218.249.0" },
    { "country": "委内瑞拉", "region": "", "province": "巴伦西亚", "isp": "movistar.net.ve", "subnet": "200.35.85.0" },
    { "country": "哥伦比亚", "region": "", "province": "波哥大", "isp": "etb.net.co", "subnet": "186.30.249.0" },
    { "country": "阿联酋", "region": "", "province": "迪拜", "isp": "du.ae", "subnet": "94.200.9.0" },
    { "country": "科威特", "region": "", "province": "科威特城", "isp": "mada.com.kw", "subnet": "213.34.207.0" },
    { "country": "沙特阿拉伯", "region": "", "province": "达曼", "isp": "mobily.com.sa", "subnet": "5.245.40.0" },
    { "country": "沙特阿拉伯", "region": "", "province": "吉达", "isp": "stc.com.sa", "subnet": "37.224.79.0" },
    { "country": "沙特阿拉伯", "region": "", "province": "利雅得", "isp": "zain.com", "subnet": "51.39.183.0" },
    { "country": "美国", "region": "西部", "province": "阿拉斯加州", "isp": "Lumen", "subnet": "216.137.192.0" },
    { "country": "美国", "region": "西部", "province": "蒙大拿州", "isp": "Lumen", "subnet": "184.166.76.0" },
    { "country": "美国", "region": "西部", "province": "科罗拉多州", "isp": "Lumen", "subnet": "64.37.30.0" },
    { "country": "美国", "region": "西部", "province": "犹他州", "isp": "Lumen", "subnet": "64.37.30.0" },
    { "country": "美国", "region": "西部", "province": "爱达荷州", "isp": "Lumen", "subnet": "160.7.240.0" },
    { "country": "美国", "region": "西部", "province": "新墨西哥州", "isp": "Lumen", "subnet": "208.80.80.0" },
    { "country": "美国", "region": "西部", "province": "怀俄明州", "isp": "Lumen", "subnet": "74.92.204.0" },
    { "country": "美国", "region": "西部", "province": "夏威夷州", "isp": "Lumen", "subnet": "209.211.254.0" },
    { "country": "美国", "region": "西部", "province": "华盛顿州", "isp": "Lumen", "subnet": "205.172.19.0" },
    { "country": "美国", "region": "西部", "province": "加利福尼亚州", "isp": "Lumen", "subnet": "72.51.45.0" },
    { "country": "美国", "region": "西部", "province": "内华达州", "isp": "Lumen", "subnet": "72.51.45.0" },
    { "country": "美国", "region": "西部", "province": "俄勒冈州", "isp": "Lumen", "subnet": "104.238.195.0" },
    { "country": "美国", "region": "西部", "province": "亚利桑那州", "isp": "Lumen", "subnet": "198.145.120.0" },
    { "country": "美国", "region": "中西部", "province": "艾奥瓦州", "isp": "Lumen", "subnet": "67.224.64.0" },
    { "country": "美国", "region": "中西部", "province": "明尼苏达州", "isp": "Lumen", "subnet": "63.231.238.0" },
    { "country": "美国", "region": "中西部", "province": "密歇根州", "isp": "Lumen", "subnet": "216.157.201.0" },
    { "country": "美国", "region": "中西部", "province": "威斯康星州", "isp": "Lumen", "subnet": "216.157.201.0" },
    { "country": "美国", "region": "中西部", "province": "印第安纳州", "isp": "Lumen", "subnet": "104.37.102.0" },
    { "country": "美国", "region": "中西部", "province": "南达科他州", "isp": "Zhejiang", "subnet": "74.221.170.0" },
    { "country": "美国", "region": "中西部", "province": "北达科他州", "isp": "Zhejiang", "subnet": "24.230.153.0" },
    { "country": "美国", "region": "中西部", "province": "内布拉斯加州", "isp": "Lumen", "subnet": "72.214.232.0" },
    { "country": "美国", "region": "中西部", "province": "俄克拉荷马州", "isp": "Zhejiang", "subnet": "74.205.88.0" },
    { "country": "美国", "region": "中西部", "province": "密苏里州", "isp": "Lumen", "subnet": "66.64.135.0" },
    { "country": "美国", "region": "中西部", "province": "堪萨斯州", "isp": "Lumen", "subnet": "216.174.63.0" },
    { "country": "美国", "region": "中西部", "province": "俄亥俄州", "isp": "Zhejiang", "subnet": "209.212.242.0" },
    { "country": "美国", "region": "东北", "province": "伊利诺伊州", "isp": "Zhejiang", "subnet": "209.212.242.0" },
    { "country": "美国", "region": "东北", "province": "马里兰州", "isp": "Lumen", "subnet": "207.172.157.0" },
    { "country": "美国", "region": "东北", "province": "马萨诸塞州", "isp": "Lumen", "subnet": "18.85.2.0" },
    { "country": "美国", "region": "东北", "province": "西弗吉尼亚州", "isp": "Lumen", "subnet": "50.121.137.0" },
    { "country": "中国", "region": "华南", "province": "广东", "isp": "腾讯云", "subnet": "182.254.34.0" },
    { "country": "中国", "region": "华东", "province": "上海", "isp": "腾讯云", "subnet": "115.159.49.0" },
    { "country": "澳大利亚", "region": "", "province": "悉尼", "isp": "阿里云", "subnet": "47.91.39.0" },
    { "country": "阿联酋", "region": "", "province": "", "isp": "阿里云", "subnet": "47.91.99.0" },
    { "country": "英国", "region": "", "province": "伦敦", "isp": "阿里云", "subnet": "8.208.8.0" },
    { "country": "德国", "region": "", "province": "法兰克福", "isp": "阿里云", "subnet": "47.254.186.0" },
    { "country": "马来西亚", "region": "", "province": "吉隆坡", "isp": "阿里云", "subnet": "47.254.218.0" },
    { "country": "新加坡", "region": "", "province": "", "isp": "阿里云", "subnet": "47.74.196.0" },
    { "country": "印度尼西亚", "region": "", "province": "雅加达", "isp": "阿里云", "subnet": "149.129.243.0" },
    { "country": "日本", "region": "", "province": "东京", "isp": "阿里云", "subnet": "47.91.8.0" },
    { "country": "中国香港", "region": "", "province": "", "isp": "阿里云", "subnet": "47.75.18.0" },
    { "country": "美国", "region": "", "province": "硅谷", "isp": "阿里云", "subnet": "47.88.73.0" },
    { "country": "美国", "region": "", "province": "弗吉尼亚", "isp": "阿里云", "subnet": "47.252.95.0" },
    { "country": "中国", "region": "华南", "province": "深圳", "isp": "阿里云", "subnet": "120.77.166.0" },
    { "country": "中国", "region": "华北", "province": "青岛", "isp": "阿里云", "subnet": "47.104.38.0" },
    { "country": "中国", "region": "华北", "province": "张家口", "isp": "阿里云", "subnet": "47.92.17.0" },
    { "country": "中国", "region": "华北", "province": "北京", "isp": "阿里云", "subnet": "59.110.190.0" },
    { "country": "中国", "region": "华东", "province": "杭州", "isp": "阿里云", "subnet": "118.31.219.0" },
    { "country": "中国", "region": "华东", "province": "上海", "isp": "阿里云", "subnet": "106.14.228.0" },
    { "country": "中国", "region": "东北", "province": "呼和浩特", "isp": "阿里云", "subnet": "39.104.9.0" },
    { "country": "澳大利亚", "region": "australia-southeast2", "province": "墨尔本", "isp": "Google", "subnet": "34.129.0.0" },
    { "country": "澳大利亚", "region": "australia-southeast1", "province": "悉尼", "isp": "Google", "subnet": "34.87.192.0" },
    { "country": "加拿大", "region": "northamerica-northeast2", "province": "多伦多", "isp": "Google", "subnet": "34.130.0.0" },
    { "country": "加拿大", "region": "northamerica-northeast1", "province": "蒙特利尔", "isp": "Google", "subnet": "34.95.0.0" },
    { "country": "智利", "region": "southamerica-west1", "province": "圣地亚哥", "isp": "Google", "subnet": "34.176.0.0" },
    { "country": "巴西", "region": "southamerica-east1", "province": "奥萨斯库", "isp": "Google", "subnet": "34.95.128.0" },
    { "country": "荷兰", "region": "europe-west4", "province": "埃姆斯哈文", "isp": "Google", "subnet": "34.90.0.0" },
    { "country": "英国", "region": "europe-west2", "province": "伦敦", "isp": "Google", "subnet": "34.89.0.0" },
    { "country": "芬兰", "region": "europe-north1", "province": "哈米纳", "isp": "Google", "subnet": "34.88.0.0" },
    { "country": "瑞士", "region": "europe-west6", "province": "苏黎世", "isp": "Google", "subnet": "34.65.0.0" },
    { "country": "比利时", "region": "europe-west1", "province": "圣吉斯兰", "isp": "Google", "subnet": "34.76.0.0" },
    { "country": "德国", "region": "europe-west3", "province": "法兰克福", "isp": "Google", "subnet": "34.89.128.0" },
    { "country": "新加坡", "region": "asia-southeast1", "province": "裕廊西", "isp": "Google", "subnet": "34.87.0.0" },
    { "country": "印度尼西亚", "region": "asia-southeast2", "province": "雅加达", "isp": "Google", "subnet": "34.101.64.0" },
    { "country": "韩国", "region": "asia-northeast3", "province": "首尔", "isp": "Google", "subnet": "34.64.192.0" },
    { "country": "日本", "region": "asia-northeast2", "province": "大阪", "isp": "Google", "subnet": "34.97.0.0" },
    { "country": "日本", "region": "asia-northeast1", "province": "东京", "isp": "Google", "subnet": "34.84.0.0" },
    { "country": "印度", "region": "asia-south2", "province": "德里", "isp": "Google", "subnet": "34.131.0.0" },
    { "country": "印度", "region": "asia-south1", "province": "孟买", "isp": "Google", "subnet": "34.93.0.0" },
    { "country": "中国香港", "region": "asia-east2", "province": "香港", "isp": "Google", "subnet": "34.92.0.0" },
    { "country": "中国台湾", "region": "asia-east1", "province": "台湾", "isp": "Google", "subnet": "34.80.0.0" },
    { "country": "美国", "region": "us-west4", "province": "斯维加斯", "isp": "Google", "subnet": "34.125.0.0" },
    { "country": "美国", "region": "us-west3", "province": "盐湖城", "isp": "Google", "subnet": "34.106.0.0" },
    { "country": "美国", "region": "us-west2", "province": "洛杉矶", "isp": "Google", "subnet": "34.94.0.0" },
    { "country": "美国", "region": "us-west1", "province": "达尔斯", "isp": "Google", "subnet": "34.82.0.0" },
    { "country": "美国", "region": "us-east4", "province": "阿什本", "isp": "Google", "subnet": "34.85.128.0" },
    { "country": "美国", "region": "us-east1", "province": "蒙克斯科纳", "isp": "Google", "subnet": "34.73.0.0" },
    { "country": "澳大利亚", "region": "ap-southeast-2", "province": "Sydney", "isp": "AWS", "subnet": "3.24.0.0" },
    { "country": "加拿大", "region": "ca-central-1", "province": "CANADA", "isp": "AWS", "subnet": "3.96.0.0" },
    { "country": "巴西", "region": "sa-east-1", "province": "SanPaulo", "isp": "AWS", "subnet": "15.228.0.0" },
    { "country": "巴林", "region": "me-south-1", "province": "Bahrain", "isp": "AWS", "subnet": "15.184.0.0" },
    { "country": "英国", "region": "eu-west-2", "province": "London", "isp": "AWS", "subnet": "3.8.0.0" },
    { "country": "瑞典", "region": "eu-north-1", "province": "Stockholm", "isp": "AWS", "subnet": "13.48.0.0" },
    { "country": "爱尔兰", "region": "eu-west-1", "province": "Ireland", "isp": "AWS", "subnet": "3.248.0.0" },
    { "country": "法国", "region": "eu-west-3", "province": "Paris", "isp": "AWS", "subnet": "13.36.0.0" },
    { "country": "意大利", "region": "eu-south-1", "province": "Milan", "isp": "AWS", "subnet": "15.161.0.0" },
    { "country": "德国", "region": "eu-central-1", "province": "Frankfurt", "isp": "AWS", "subnet": "3.120.0.0" },
    { "country": "新加坡", "region": "ap-southeast-1", "province": "Singapore", "isp": "AWS", "subnet": "3.0.0.0" },
    { "country": "韩国", "region": "ap-northeast-2", "province": "Seoul", "isp": "AWS", "subnet": "3.34.0.0" },
    { "country": "日本", "region": "ap-northeast-3", "province": "Osaka-Local", "isp": "AWS", "subnet": "13.208.32.0" },
    { "country": "日本", "region": "ap-northeast-1", "province": "Tokyo", "isp": "AWS", "subnet": "3.112.0.0" },
    { "country": "印度", "region": "ap-south-1", "province": "Mumbai", "isp": "AWS", "subnet": "3.6.0.0" },
    { "country": "中国香港", "region": "ap-east-1", "province": "HongKong", "isp": "AWS", "subnet": "18.162.80.0" },
    { "country": "南非", "region": "af-south-1", "province": "CapeTown", "isp": "AWS", "subnet": "13.245.0.0" },
    { "country": "美国", "region": "us-west-2-lax-1", "province": "LosAngeles", "isp": "AWS", "subnet": "15.253.0.0" },
    { "country": "美国", "region": "us-west-2", "province": "USA-Oregon", "isp": "AWS", "subnet": "18.236.0.0" },
    { "country": "美国", "region": "us-west-1", "province": "NorthCalifornia", "isp": "AWS", "subnet": "13.52.0.0" },
    { "country": "美国", "region": "us-gov-west-1", "province": "GovCloud-US-West", "isp": "AWS", "subnet": "3.32.0.0" },
    { "country": "美国", "region": "us-gov-east-1", "province": "GovCloud-US-East", "isp": "AWS", "subnet": "18.252.0.0" },
    { "country": "美国", "region": "us-east-2", "province": "Ohio", "isp": "AWS", "subnet": "3.12.0.0" },
    { "country": "美国", "region": "us-east-1", "province": "NorthVirginia", "isp": "AWS", "subnet": "3.80.0.0" },
    { "country": "中国", "region": "cn-northwest-1", "province": "Ningxia", "isp": "AWS", "subnet": "52.82.0.0" },
    { "country": "中国", "region": "cn-north-1", "province": "Beijing", "isp": "AWS", "subnet": "52.80.5.0" },
    { "country": "美国", "region": "西部", "province": "加利福尼亚", "isp": "谷歌", "subnet": "66.249.79.0" },
    { "country": "中国", "region": "华东", "province": "上海", "isp": "神马", "subnet": "42.120.161.0" },
    { "country": "中国", "region": "华北", "province": "北京", "isp": "百度", "subnet": "220.181.108.0" },
    { "country": "中国", "region": "华北", "province": "北京", "isp": "搜狗", "subnet": "106.38.241.0" }
];